DEFAULT_CONFIG = {
    "altitude_m": 0.0,
    "ambient_temperature": None,
    "ambient_pressure": None,
    "flight_speed": 200.0,
    "mass_flow_rate": 10.0,
    "pressure_recovery": 0.98,
    "diffuser_exit_velocity": 85.0,
    "compressor_pressure_ratio": 10.0,
    "compressor_efficiency": 0.85,
    "compressor_exit_velocity": 120.0,
    "turbine_inlet_temperature": 1500.0,
    "combustor_pressure_loss": 0.05,
    "combustor_efficiency": 0.99,
    "combustor_exit_velocity": 70.0,
    "turbine_efficiency": 0.90,
    "mechanical_efficiency": 0.95,
    "turbine_exit_velocity": 150.0,
    "afterburner_enabled": False,
    "afterburner_exit_temperature": 1800.0,
    "afterburner_pressure_loss": 0.04,
    "afterburner_efficiency": 0.98,
    "afterburner_exit_velocity": 170.0,
    "nozzle_efficiency": 0.97,
    "gas_name": "Air",
    "gas_cp": 1005.0,
    "gas_gamma": 1.4,
    "fuel_lower_heating_value": 43_000_000.0,
    "export_png": False,
    "verbose": True,
}


def get_default_config():
    return dict(DEFAULT_CONFIG)
